#!/usr/bin/env python3
"""Generate tools/seeds/java.json from a compact, reviewable package list.

Run from the repo root after editing PACKAGES below:
    python tools/build_seed_list.py
"""
from __future__ import annotations

import json
from pathlib import Path


# (groupId, artifactId, [tags])
PACKAGES = [
    ("org.springframework", "spring-context", ["IoC", "依赖注入", "Web框架"]),
    ("org.springframework", "spring-core", ["IoC", "核心工具"]),
    ("org.springframework", "spring-web", ["Web框架", "HTTP"]),
    ("org.springframework", "spring-webmvc", ["Web框架", "MVC"]),
    ("org.springframework", "spring-jdbc", ["数据库", "JDBC"]),
    ("org.springframework.boot", "spring-boot", ["Web框架", "微服务"]),
    ("org.springframework.boot", "spring-boot-autoconfigure", ["Web框架", "自动配置"]),
    ("org.springframework.boot", "spring-boot-starter-web", ["Web框架", "微服务"]),
    ("org.springframework.boot", "spring-boot-starter-test", ["测试"]),
    ("org.springframework.boot", "spring-boot-starter-security", ["安全", "认证"]),
    ("org.springframework.security", "spring-security-core", ["安全", "认证"]),
    ("org.springframework.cloud", "spring-cloud-starter-gateway", ["微服务", "网关"]),
    ("org.springframework.kafka", "spring-kafka", ["消息队列", "Kafka"]),
    ("org.apache.commons", "commons-lang3", ["工具库"]),
    ("org.apache.commons", "commons-collections4", ["集合", "工具库"]),
    ("org.apache.commons", "commons-io", ["IO", "工具库"]),
    ("org.apache.commons", "commons-math3", ["数学", "统计"]),
    ("org.apache.commons", "commons-text", ["文本", "工具库"]),
    ("org.apache.commons", "commons-compress", ["压缩", "工具库"]),
    ("org.apache.commons", "commons-csv", ["CSV", "解析"]),
    ("org.apache.commons", "commons-pool2", ["对象池"]),
    ("commons-io", "commons-io", ["IO", "工具库"]),
    ("commons-logging", "commons-logging", ["日志"]),
    ("commons-codec", "commons-codec", ["编码", "加密"]),
    ("commons-validator", "commons-validator", ["校验"]),
    ("commons-beanutils", "commons-beanutils", ["Bean", "反射"]),
    ("commons-dbcp2", "commons-dbcp2", ["连接池", "数据库"]),
    ("commons-fileupload", "commons-fileupload", ["文件上传", "Web"]),
    ("org.apache.httpcomponents", "httpclient", ["HTTP客户端"]),
    ("org.apache.httpcomponents.client5", "httpclient5", ["HTTP客户端"]),
    ("org.apache.httpcomponents.core5", "httpcore5", ["HTTP", "网络"]),
    ("org.apache.poi", "poi", ["Office", "Excel", "Word"]),
    ("org.apache.poi", "poi-ooxml", ["Office", "Excel", "Word"]),
    ("org.apache.pdfbox", "pdfbox", ["PDF", "文档处理"]),
    ("org.apache.tika", "tika-core", ["文档解析", "文本提取"]),
    ("org.apache.kafka", "kafka-clients", ["消息队列", "Kafka"]),
    ("org.apache.kafka", "kafka-streams", ["流计算", "Kafka"]),
    ("org.apache.zookeeper", "zookeeper", ["分布式协调"]),
    ("org.apache.dubbo", "dubbo", ["RPC", "微服务"]),
    ("org.apache.rocketmq", "rocketmq-client", ["消息队列"]),
    ("org.apache.activemq", "activemq-client", ["消息队列"]),
    ("org.apache.activemq", "activemq-all", ["消息队列"]),
    ("org.apache.pulsar", "pulsar-client", ["消息队列", "流计算"]),
    ("org.apache.curator", "curator-framework", ["分布式协调", "ZooKeeper"]),
    ("org.apache.curator", "curator-recipes", ["分布式协调", "分布式锁"]),
    ("org.apache.tomcat", "tomcat-catalina", ["Web服务器", "Servlet"]),
    ("org.apache.tomcat.embed", "tomcat-embed-core", ["Web服务器", "嵌入式"]),
    ("org.apache.velocity", "velocity-engine-core", ["模板引擎"]),
    ("org.apache.freemarker", "freemarker", ["模板引擎"]),
    ("org.apache.lucene", "lucene-core", ["全文检索"]),
    ("org.apache.solr", "solr-core", ["全文检索", "搜索引擎"]),
    ("org.apache.hadoop", "hadoop-common", ["大数据", "分布式存储"]),
    ("org.apache.spark", "spark-core_2.13", ["大数据", "计算引擎"]),
    ("org.apache.spark", "spark-sql_2.13", ["大数据", "SQL"]),
    ("org.apache.flink", "flink-core", ["流计算", "大数据"]),
    ("org.apache.flink", "flink-java", ["流计算", "Java"]),
    ("org.apache.flink", "flink-streaming-java", ["流计算", "大数据"]),
    ("org.apache.hive", "hive-common", ["数据仓库", "SQL"]),
    ("org.apache.hbase", "hbase-client", ["NoSQL", "分布式数据库"]),
    ("org.apache.cassandra", "cassandra-all", ["NoSQL", "分布式数据库"]),
    ("org.apache.calcite", "calcite-core", ["SQL", "查询优化"]),
    ("org.apache.iceberg", "iceberg-core", ["数据湖", "表格式"]),
    ("org.apache.hudi", "hudi-common", ["数据湖", "表格式"]),
    ("org.apache.arrow", "arrow-memory-core", ["列式存储", "大数据"]),
    ("org.apache.parquet", "parquet-hadoop", ["列式存储", "大数据"]),
    ("org.apache.avro", "avro", ["序列化", "大数据"]),
    ("org.apache.orc", "orc-core", ["列式存储", "大数据"]),
    ("org.apache.maven", "maven-core", ["构建工具"]),
    ("org.apache.maven.plugins", "maven-compiler-plugin", ["构建插件"]),
    ("org.apache.maven.plugins", "maven-surefire-plugin", ["构建插件", "测试"]),
    ("org.apache.maven.plugins", "maven-shade-plugin", ["构建插件"]),
    ("org.apache.maven.plugins", "maven-dependency-plugin", ["构建插件"]),
    ("org.apache.maven.plugins", "maven-assembly-plugin", ["构建插件"]),
    ("org.apache.maven.plugins", "maven-jar-plugin", ["构建插件"]),
    ("org.apache.maven.plugins", "maven-release-plugin", ["构建插件", "发布"]),
    ("org.apache.maven.wagon", "wagon-http", ["构建工具"]),
    ("org.codehaus.plexus", "plexus-utils", ["工具库"]),
    ("org.codehaus.mojo", "exec-maven-plugin", ["构建插件"]),
    ("org.codehaus.mojo", "versions-maven-plugin", ["构建插件"]),
    ("com.google.guava", "guava", ["工具库", "集合"]),
    ("com.google.code.gson", "gson", ["JSON", "序列化"]),
    ("com.google.protobuf", "protobuf-java", ["序列化", "RPC"]),
    ("com.google.inject", "guice", ["IoC", "依赖注入"]),
    ("com.google.http-client", "google-http-client", ["HTTP客户端"]),
    ("com.google.api-client", "google-api-client", ["API客户端"]),
    ("com.google.errorprone", "error_prone_annotations", ["代码检查"]),
    ("com.google.truth", "truth", ["测试", "断言"]),
    ("com.google.zxing", "core", ["二维码", "条码"]),
    ("com.google.cloud", "google-cloud-storage", ["云存储", "GCP"]),
    ("com.google.firebase", "firebase-admin", ["云服务", "Firebase"]),
    ("com.fasterxml.jackson.core", "jackson-databind", ["JSON", "序列化"]),
    ("com.fasterxml.jackson.core", "jackson-core", ["JSON", "流式解析"]),
    ("com.fasterxml.jackson.core", "jackson-annotations", ["JSON", "注解"]),
    ("com.fasterxml.jackson.dataformat", "jackson-dataformat-xml", ["XML", "序列化"]),
    ("com.fasterxml.jackson.dataformat", "jackson-dataformat-yaml", ["YAML", "序列化"]),
    ("com.fasterxml.jackson.dataformat", "jackson-dataformat-csv", ["CSV", "序列化"]),
    ("com.fasterxml.jackson.datatype", "jackson-datatype-jsr310", ["JSON", "日期时间"]),
    ("com.fasterxml.jackson.module", "jackson-module-kotlin", ["JSON", "Kotlin"]),
    ("com.squareup.okhttp3", "okhttp", ["HTTP客户端"]),
    ("com.squareup.okio", "okio", ["IO", "工具库"]),
    ("com.squareup.retrofit2", "retrofit", ["HTTP客户端", "REST"]),
    ("com.squareup.picasso", "picasso", ["图片加载"]),
    ("com.squareup.moshi", "moshi", ["JSON", "序列化"]),
    ("com.squareup.javapoet", "javapoet", ["代码生成"]),
    ("io.reactivex.rxjava2", "rxjava", ["响应式编程"]),
    ("io.reactivex.rxjava3", "rxjava", ["响应式编程"]),
    ("io.projectreactor", "reactor-core", ["响应式编程"]),
    ("io.projectreactor", "reactor-test", ["响应式编程", "测试"]),
    ("io.projectreactor.netty", "reactor-netty", ["响应式编程", "网络"]),
    ("io.netty", "netty-all", ["网络框架"]),
    ("io.netty", "netty-buffer", ["网络框架", "缓冲区"]),
    ("io.netty", "netty-codec-http", ["网络框架", "HTTP"]),
    ("io.netty", "netty-codec-http2", ["网络框架", "HTTP/2"]),
    ("io.netty", "netty-codec-mqtt", ["网络框架", "MQTT"]),
    ("io.netty", "netty-handler", ["网络框架"]),
    ("io.netty", "netty-transport", ["网络框架"]),
    ("io.vertx", "vertx-core", ["网络框架", "异步编程"]),
    ("io.vertx", "vertx-web", ["Web框架"]),
    ("io.grpc", "grpc-netty-shaded", ["RPC", "gRPC"]),
    ("io.grpc", "grpc-protobuf", ["RPC", "gRPC"]),
    ("io.grpc", "grpc-stub", ["RPC", "gRPC"]),
    ("io.jsonwebtoken", "jjwt-api", ["JWT", "安全"]),
    ("io.jsonwebtoken", "jjwt-jackson", ["JWT", "安全"]),
    ("io.dropwizard.metrics", "metrics-core", ["监控", "指标"]),
    ("io.prometheus", "simpleclient", ["监控", "指标"]),
    ("io.micrometer", "micrometer-core", ["监控", "指标"]),
    ("io.opentelemetry", "opentelemetry-api", ["链路追踪", "可观测性"]),
    ("io.opentelemetry", "opentelemetry-sdk", ["链路追踪", "可观测性"]),
    ("io.zipkin.brave", "brave", ["链路追踪"]),
    ("io.lettuce", "lettuce-core", ["Redis", "NoSQL"]),
    ("redis.clients", "jedis", ["Redis", "NoSQL"]),
    ("org.redisson", "redisson", ["Redis", "分布式锁"]),
    ("com.mongodb", "mongodb-driver-sync", ["NoSQL", "MongoDB"]),
    ("com.mongodb", "mongodb-driver-core", ["NoSQL", "MongoDB"]),
    ("org.elasticsearch", "elasticsearch", ["搜索引擎", "全文检索"]),
    ("org.elasticsearch.client", "elasticsearch-rest-client", ["搜索引擎", "客户端"]),
    ("co.elastic.clients", "elasticsearch-java", ["搜索引擎", "客户端"]),
    ("org.mybatis", "mybatis", ["ORM", "数据库"]),
    ("org.mybatis", "mybatis-spring", ["ORM", "Spring集成"]),
    ("com.baomidou", "mybatis-plus", ["ORM", "增强"]),
    ("org.hibernate.orm", "hibernate-core", ["ORM", "数据库"]),
    ("org.hibernate.validator", "hibernate-validator", ["校验"]),
    ("org.jdbi", "jdbi3-core", ["数据库", "SQL"]),
    ("org.jooq", "jooq", ["数据库", "SQL"]),
    ("com.zaxxer", "HikariCP", ["连接池"]),
    ("com.alibaba", "druid", ["连接池", "监控"]),
    ("com.alibaba", "fastjson", ["JSON", "序列化"]),
    ("org.postgresql", "postgresql", ["数据库驱动", "PostgreSQL"]),
    ("com.mysql", "mysql-connector-j", ["数据库驱动", "MySQL"]),
    ("com.microsoft.sqlserver", "mssql-jdbc", ["数据库驱动", "SQL Server"]),
    ("org.xerial", "sqlite-jdbc", ["数据库驱动", "SQLite"]),
    ("com.h2database", "h2", ["数据库", "内存数据库"]),
    ("org.flywaydb", "flyway-core", ["数据库迁移"]),
    ("org.liquibase", "liquibase-core", ["数据库迁移"]),
    ("org.mapstruct", "mapstruct", ["代码生成", "对象映射"]),
    ("org.projectlombok", "lombok", ["代码生成", "注解"]),
    ("org.jetbrains", "annotations", ["注解", "空安全"]),
    ("org.jetbrains.kotlin", "kotlin-stdlib", ["语言", "Kotlin"]),
    ("org.jetbrains.kotlinx", "kotlinx-coroutines-core", ["协程", "异步编程"]),
    ("org.jetbrains.kotlinx", "kotlinx-serialization-json", ["JSON", "序列化"]),
    ("org.scala-lang", "scala-library", ["语言", "Scala"]),
    ("org.junit.jupiter", "junit-jupiter", ["测试", "单元测试"]),
    ("org.junit.jupiter", "junit-jupiter-api", ["测试", "单元测试"]),
    ("org.junit.platform", "junit-platform-launcher", ["测试"]),
    ("junit", "junit", ["测试", "单元测试"]),
    ("org.testng", "testng", ["测试", "单元测试"]),
    ("org.assertj", "assertj-core", ["测试", "断言"]),
    ("org.hamcrest", "hamcrest", ["测试", "断言"]),
    ("org.mockito", "mockito-core", ["测试", "Mock"]),
    ("org.mockito", "mockito-junit-jupiter", ["测试", "Mock"]),
    ("org.testcontainers", "testcontainers", ["测试", "容器"]),
    ("org.testcontainers", "junit-jupiter", ["测试", "容器"]),
    ("org.awaitility", "awaitility", ["测试", "异步"]),
    ("org.openjdk.jmh", "jmh-core", ["性能测试", "基准测试"]),
    ("org.jacoco", "org.jacoco.core", ["代码覆盖率"]),
    ("org.sonarsource.scanner.maven", "sonar-maven-plugin", ["代码质量"]),
    ("jakarta.xml.bind", "jakarta.xml.bind-api", ["XML绑定", "JAXB"]),
    ("jakarta.persistence", "jakarta.persistence-api", ["ORM", "JPA规范"]),
    ("jakarta.validation", "jakarta.validation-api", ["校验", "规范"]),
    ("jakarta.servlet", "jakarta.servlet-api", ["Web", "Servlet规范"]),
    ("javax.servlet", "javax.servlet-api", ["Web", "Servlet规范"]),
    ("javax.persistence", "javax.persistence-api", ["ORM", "JPA规范"]),
    ("jakarta.inject", "jakarta.inject-api", ["IoC", "依赖注入", "规范"]),
    ("javax.inject", "javax.inject", ["IoC", "依赖注入", "规范"]),
    ("org.eclipse.jetty", "jetty-server", ["Web服务器"]),
    ("org.eclipse.jetty", "jetty-servlet", ["Web服务器"]),
    ("org.eclipse.jgit", "org.eclipse.jgit", ["Git", "版本控制"]),
    ("org.glassfish.jersey.core", "jersey-client", ["REST", "JAX-RS"]),
    ("org.glassfish.jersey.core", "jersey-server", ["REST", "JAX-RS"]),
    ("org.glassfish.jaxb", "jaxb-runtime", ["XML绑定", "JAXB"]),
    ("com.sun.mail", "jakarta.mail", ["邮件"]),
    ("org.jsoup", "jsoup", ["HTML解析", "爬虫"]),
    ("com.microsoft.playwright", "playwright", ["浏览器自动化"]),
    ("org.seleniumhq.selenium", "selenium-java", ["浏览器自动化", "测试"]),
    ("io.github.bonigarcia", "webdrivermanager", ["浏览器自动化", "驱动管理"]),
    ("us.codecraft", "webmagic-core", ["爬虫"]),
    ("com.github.resilience4j", "resilience4j-circuitbreaker", ["容错", "熔断"]),
    ("com.github.resilience4j", "resilience4j-ratelimiter", ["限流", "容错"]),
    ("com.github.resilience4j", "resilience4j-retry", ["重试", "容错"]),
    ("org.quartz-scheduler", "quartz", ["定时任务"]),
    ("com.github.oshi", "oshi-core", ["系统信息", "监控"]),
    ("com.sun.jna", "jna", ["本地调用", "JNI"]),
    ("info.picocli", "picocli", ["命令行", "CLI"]),
    ("org.apache.ant", "ant", ["构建工具"]),
    ("org.slf4j", "slf4j-api", ["日志"]),
    ("ch.qos.logback", "logback-classic", ["日志"]),
    ("org.apache.logging.log4j", "log4j-core", ["日志"]),
    ("org.apache.logging.log4j", "log4j-api", ["日志"]),
]


def main() -> None:
    out = Path(__file__).resolve().parent / "seeds" / "java.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    seen = set()
    for group, artifact, tags in PACKAGES:
        key = (group, artifact)
        if key in seen:
            continue
        seen.add(key)
        rows.append({"group": group, "artifact": artifact, "tags": tags})
    out.write_text(json.dumps(rows, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(rows)} packages to {out}")


if __name__ == "__main__":
    main()
